### ISSUE TITLE
Token expiry time

### ISSUE THREAD

**Issue by Danbardo** [jasonjoh/javascript-tutorial#2]
Hey Jason,

Is it possible to extend the life of a token to a day or week? 

I am trying to continuously keep users calendars up to date, while trying to minimize the number of times they have to login to their accounts.

Can you use the Javascript API to write as well? In particular, I haven't found any information about adding attendee's to calendar events using the Graph API.

Thanks in advance

**Comment by jasonjoh** [comment]
No. Access tokens are only good for one hour. You should be able to silently acquire a new one as long as the browser is open to your page though. If you're updating calendars in a background process, or from the backend, you shouldn't use javascript on the client, which only supports implicit flow. You could move your code to the server and do an auth code flow that gets you a refresh token. Look at https://docs.microsoft.com/en-us/outlook/rest/get-started for tutorials on a number of different backend techs (Node, .NET, etc).

You can use the API to write, you would need to request the write scopes (for example, instead of `Calendars.Read`, you'd use `Calendars.ReadWrite`).

**Comment by Danbardo** [comment]
Thanks heaps Jason.

Is it possible to set up the code on my server using an app created in the Outlook Dev Portal?

What's the difference between that and the Azure AD created apps?

I was having a bunch of trouble, but thought the Javascript solve my problem.
https://github.com/jasonjoh/php-calendar/issues/5

**Comment by jasonjoh** [comment]
What do you mean by "an app created in the Outlook Dev Portal"?

**Comment by Danbardo** [comment]
One that I create here:
https://dev.outlook.com/appregistration
Rather than within Azure AD.

**Comment by jasonjoh** [comment]
Ah ok. I shut down that page long ago, but forgot it redirects to the App Registration portal. Apps created there can be registered using a personal account (like Outlook.com accounts), and that enables personal accounts to log in to your app. Azure AD created apps don't support personal accounts.
